app_name: pet-battle
replicas: 1
# build info not used atm
build:
  enabled: false
  build_tag: latest
  source_docker_file_path: Dockerfile
  # source_context_dir: "/"
  # source_ref: master
  # source_repo: https://github.com/springdo/pet-battle.git
# Docker deets
image_repository: quay.io
image_name: pet-battle
image_namespace: petbattle
# likely over written by the Argo definition
app_tag: latest

# OCP route
route: true
# custom end point injected by config map. This is likely to changed
config_map: "'http://pet-battle-api-cats.apps.s44.core.rht-labs.com'"

# service mesh
istio:
  enabled: false
  mtls: true
  domain: apps.hivec.sandbox209.opentlc.com